### ISSUE TITLE
Attribute types incompatibility on WordPress 5.5

### ISSUE THREAD

**Issue by toufic-m** [10up/brightcove-video-connect#172]
**Describe the bug**

As of WordPress 5.5 (#171), the plugin throws the following notice when debug mode is enabled:

> Notice: rest_validate_value_from_schema was called <strong>incorrectly</strong>. The "type" schema keyword for can only be one of the built-in types: array, object, string, number, integer, boolean, and null. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 5.5.0.)

This notice is originating from the use of `int` (as opposed to the supported built-in type: `integer`) for attribute types that are used for registering the `bc/brightcove` block.
https://github.com/10up/brightcove-video-connect/blob/e99b9e05bca8eacb833b4b19ef9fbedfb5336cb4/includes/class-bc-setup.php#L121-L142

**Steps to Reproduce**

1. Enable debug mode, by defining `WP_DEBUG` as `true`
2. Go to a post creation/editing screen
3. See notice (the notice is visible for a few seconds before the Gutenberg block editor has loaded; once the the editor has loaded, the notice would be "covered" by the editor, but would still be present in the page's source code)

**Expected behavior**

WordPress would no longer be throwing these notices once the attribute types are changed from `int` to `integer`.

**Environment information**
 - WordPress version: 5.5

**Additional context**

https://make.wordpress.org/core/2020/07/16/rest-api-parameter-json-schema-changes-in-wordpress-5-5/

**Comment by toufic-m** [comment]
Follow-up to the above: simply changing the existing attribute types from `int` to `integer` does in fact prevent the warnings, but is not enough, and would require additional changes to the plugin's codebase, as it would not be compatible with the current version of the plugin, nor backwards-compatible with pre-existing Brightcove video blocks in the Gutenberg editor, that were added in older versions of WordPress. Whereas, changing the attribute types to `string` seems to be fully compatible so far.

https://developer.wordpress.org/block-editor/developers/block-api/block-attributes/

**Comment by mollfrey** [comment]
This issue appears to persist in WordPress 5.6

**Comment by Rahmon** [comment]
A possible workaround is to change these attributes using the filter register_block_type_args:

```php
add_filter(
	'register_block_type_args',
	function ( $args, $block_type ) {
		if ( 'bc/brightcove' === $block_type ) {
			$args['attributes']['account_id']['type']  = 'string';
			$args['attributes']['video_id']['type']    = 'string';
			$args['attributes']['playlist_id']['type'] = 'string';
			$args['attributes']['video_ids']['type']   = 'string';
		}

		return $args;
	},
	10,
	2
);
```
