### ISSUE TITLE
Filtering inactive videos in video selector

### ISSUE THREAD

**Issue by sbabar79** [10up/brightcove-video-connect#173]
I tried looking for any configuration to disable inactive videos in video selector gallery window but cant find one. I have issue with lots of videos which are inactive or deactivated are also showing up on video selector when embeding or selecting a feature video for pages/articles. Users do select these videos which dont play when published.
How can we disable listing of inactive videos to avoide selection ?
Perhaps this can be featured enhancement as configuration on settings.

**Comment by oscarssanchez** [comment]
Hi @sbabar79 ,

We have worked this on https://github.com/10up/brightcove-video-connect/pull/174 and are aiming to merge this on our upcoming release. 

Kind regards,

**Comment by sbabar79** [comment]
Thanks @oscarssanchez I got the new release and it shows the state drop down with (all states|active|inactive). This works well.
Is there anyway we could make Active as default value ?
