### ISSUE TITLE
Allow to set the default video state on configuration

### ISSUE THREAD

**Issue by brunomoutinho** [10up/brightcove-video-connect#178]
Recently you have published an enhancement  that allows the user to filter videos based on their state: "Active" or "Inactive". It would be good if we could set the default behavior of that filter.

**Is your enhancement related to a problem? Please describe.**

Whenever I open the Brightcove video page, I want the videos to come filtered based on the default configuration I set for state value.

**Describe the solution you'd like**

Filter videos with either "Active" or "Inactive" state by default, based on configuration (it could be either code configuration, so that when I add the plugin I can set the default behavior or on the configurations' page).

**Designs**

**Describe alternatives you've considered**

**Additional context**

**Comment by brunomoutinho** [comment]
@oscarssanchez it seems to me that the PR has been approved: https://github.com/10up/brightcove-video-connect/pull/179
Could you take a look, please? Thank you!

**Comment by oscarssanchez** [comment]
Closing per #179
