### ISSUE TITLE
Uncaught Error: Cannot use object of type WP_Error as array in brightcove-video-connect/includes/api/class-bc-cms-api.php:804

### ISSUE THREAD

**Issue by 84em** [10up/brightcove-video-connect#188]
When activating the plugin I receive the following error.

Uncaught Error: Cannot use object of type WP_Error as array in brightcove-video-connect/includes/api/class-bc-cms-api.php:804

Changing the method to this, fixes the issue:

```
public function get_account_labels() {
	$result = $this->send_request( esc_url_raw( self::CMS_BASE_URL . $this->get_account_id() . '/labels/' ), 'GET' );
	if ( is_wp_error( $result) || empty( $result['labels'] ) ) {
		return false;
	}
	return $result['labels'];
}

```

**Comment by oscarssanchez** [comment]
Hi @84em ,

Thanks for flagging this! We have merged the fix for it and it should be out soon.
