### ISSUE TITLE
Test against WordPress 5.7

### ISSUE THREAD

**Issue by jeffpaul** [10up/brightcove-video-connect#199]
**Is your enhancement related to a problem? Please describe.**
 Once WordPress 5.7 is released, we'll want to test Brightcove Video Connect to see if any incompatibility issues arise.

**Describe the solution you'd like**
- [ ] test Brightcove Video Connect on WordPress 5.7
- [ ] open issues for any incompatibilities noted in testing
- [ ] resolve issues identified in testing
- [ ] bump "tested up to" version
- [ ] if code changes needed due to incompatibilities, ship a plugin release, otherwise use "Plugin asset/readme update" action to update "tested up to" version on .org repo

**Designs**
n/a

**Describe alternatives you've considered**
none

**Additional context**
Related: https://github.com/10up/brightcove-video-connect/issues/161, https://github.com/10up/brightcove-video-connect/issues/171.

**Comment by Rahmon** [comment]
Closed via [2.1.4 release](https://github.com/10up/brightcove-video-connect/pull/211)
