### ISSUE TITLE
Playlist not being applied to experience

### ISSUE THREAD

**Issue by william-klus** [10up/brightcove-video-connect#270]
### Describe the bug

Hello Everyone,

When using the plugin I noticed that the playlist experience is not working. When I choose "Playlist Experience" choose the playlist and choose the experience player it displays properly in the edit page but on the live page it does not choose the playlist.

I can see what the issue is. It looks like the "data-playlist-id" data attribute is not being added to the div in the live page. It is using "data-video-ids" instead and its empty. it is working in the edit page because it looks like the edit page displays the preview in and iframe with "?playlistId=XXXXXX" at the end of the url.

So the bug looks like it is due to the experience div not having the "data-playlist-id" attribute. I've added a screenshot of the html of the live page. It shows the Brightcove html which is not working and it shows me using the html block with the playlist overide working. 

### Steps to Reproduce

1. got to playlist experience 
2. Select playlist and experience player
3. view page and playlist not showing

### Screenshots, screen recording, code snippet

![playlist-bug](https://user-images.githubusercontent.com/59928165/165553132-50b20294-563b-4d2e-8bc2-d7a564e1ba68.jpg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oscarssanchez** [comment]
Fixed in https://github.com/10up/brightcove-video-connect/pull/322
