### ISSUE TITLE
Help notices being displayed more than once

### ISSUE THREAD

**Issue by felipeelia** [10up/brightcove-video-connect#344]
### Describe the bug

Clicking on "help" displays the help notice more than once.

### Steps to Reproduce

1. Go to /wp-admin/admin.php?page=page-brightcove-videos#
2. Click on "help" (aside search form)

### Screenshots, screen recording, code snippet

![image](https://github.com/10up/brightcove-video-connect/assets/184628/064efdcf-218e-42e7-8e5c-368803973571)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rfiguerasbcov** [comment]
Replace before releasing 2.8.4, seems a small cosmetic thing.
