### ISSUE TITLE
Videos page and navigation

### ISSUE THREAD

**Issue by felipeelia** [10up/brightcove-video-connect#345]
### Is your enhancement related to a problem? Please describe.

Navigating the videos list page (wp-admin/admin.php?page=page-brightcove-videos) can be more intuitive:

1. Clicking on a video and then on "Edit" open the video details to be edited. The only way to go back is to scroll down to the bottom and click "Back". Hitting "Back" on the browser or reloading the page has an unexpected behavior.
2. Clicking on "Edit" on an Inactive video goes to a blank page.

https://github.com/10up/brightcove-video-connect/assets/184628/63f2ae23-c047-4016-9dca-ea13f0db0e78

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rfiguerasbcov** [comment]
I'd do this for 2.8.5, so after we send the notification around 2.8.4 and tell them that support below X will stop...
