### ISSUE TITLE
Move playlists notice outside the controls bar

### ISSUE THREAD

**Issue by felipeelia** [10up/brightcove-video-connect#346]
### Is your enhancement related to a problem? Please describe.

Usually, WordPress notices are displayed above everything else. The playlist page does not follow that:

1. How it is now:
![image](https://github.com/10up/brightcove-video-connect/assets/184628/95167d69-2b85-4e18-88ae-ff5aed0292a5)

2. How it should be:
![image](https://github.com/10up/brightcove-video-connect/assets/184628/2637da98-4110-44ff-ac32-cc858fb2324d)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rfiguerasbcov** [comment]
I'd do this for 2.8.5, so after we send the notification around 2.8.4 and tell them that support below X will stop...
