### ISSUE TITLE
Playlists: Empty "Created At:" and "Updated At:"

### ISSUE THREAD

**Issue by felipeelia** [10up/brightcove-video-connect#347]
### Is your enhancement related to a problem? Please describe.

Clicking on a playlist, always display empty "Created At" and "Updated At" values:

![image](https://github.com/10up/brightcove-video-connect/assets/184628/54adeb0a-9851-4543-bfab-d3304f06bdc8)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rfiguerasbcov** [comment]
Seems small, I'd do for 2.8.4.
