### ISSUE TITLE
Search box is not aligned.

### ISSUE THREAD

**Issue by burhandodhy** [10up/brightcove-video-connect#352]
### Describe the bug

The search box is not aligned in the "Brightcove Media Model"

<img width="2505" alt="image" src="https://github.com/10up/brightcove-video-connect/assets/7139602/b9dd04ac-1f46-4071-a5c7-5b2b50cea9a2">

### Steps to Reproduce

1. Enable the Classic Editor plugin
2. Go to Post
3. Click on the "Brightcove Media" button

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cjacobop** [comment]
@MARQAS @burhandodhy How do we enable the Classic Editor plugin?
