### ISSUE TITLE
Deprecated warnings on PHP 8.2

### ISSUE THREAD

**Issue by burhandodhy** [10up/brightcove-video-connect#353]
### Describe the bug

The plugin is throwing the deprecated warning on the admin dashboard

`strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated`

`str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated`

### Steps to Reproduce

1. Make sure that the plugin is running on PHP 8.2
2. Go to the admin dashboard

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jonnynews** [comment]
Also seeing this in my logs. Would love to see it fixed.
