### ISSUE TITLE
Failing experiences REST API request

### ISSUE THREAD

**Issue by jonnynews** [10up/brightcove-video-connect#367]
### Describe the bug

When opening the CMS / WP-admin, I noticed there is a failed REST API call to the `experiences` API. This API gets a 403 returned stated ( see screenshot ). As this request returns with an error state ( 403 ), this API request is not cached. This uncached API request happens on every page load, slowing down the responsiveness of WordPress. 

### Steps to Reproduce

1. Setup plugin. 
2. Install and activate [query monitor](https://wordpress.org/plugins/query-monitor/). 
3. Go to wp-admin. 
4. See failed REST API request. ( See screenshot ). 

### Screenshots, screen recording, code snippet

<img width="1629" alt="Screenshot 2023-12-01 at 13 03 52" src="https://github.com/10up/brightcove-video-connect/assets/148061917/e580d3f0-22b8-4761-82fa-492f6312ae9a">

### WordPress information

WP: 6.2.
Brightcove: 2.8.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by spacedmonkey** [comment]
This is a pretty major bug, any chance someone could look into this. CC @felipeelia
