### ISSUE TITLE
Video insert does not work from video edit page

### ISSUE THREAD

**Issue by bc-timbaldwin** [10up/brightcove-video-connect#38]
A video is not successfully inserted into an article following the steps below:
1. Click on *Brightcove Media* button from an article
2. Click on a video from those shown in the Brightcove *Videos* tab
3. Click on the *Edit* button
4. Click on *Insert into Post* button

However, if you click on *Insert to Post* from the *Videos* tab and not on the *Edit* page, the video is successfully inserted into the article.  

This may be related to the fix of an issue from v1.2.1 and prior where the video would appear as "There was a problem displaying the video player" when it was inserted via the *Edit* page.

**Comment by davidrgreen** [comment]
Thanks for the detailed steps to reproduce. I've confirmed the issue and we'll be addressing it ASAP.
