### ISSUE TITLE
Limit BC API checks in BC_Status_Warning

### ISSUE THREAD

**Issue by joshlevinson** [10up/brightcove-video-connect#53]
Currently, BC_Status_Warning is initialized and executes a blocking HTTP request on every request that `is_admin()`. Metrics on a site I'm optimizing show this introducing 250ms on every admin request.
I suggest:

1. `BC_Status_Warning::_check_for_failed` should be limited in how often it performs the API status check. Currently, the *processed* results of the check are stored in a transient, but the remote request is still performed on every admin request. IMO, it makes more sense to wrap the entire `_check_for_failed` method in cache, rather than the processed results, the latter of which are likely much less expensive than the actual request.
2. Limit the scope of `BC_Status_Warning::_check_for_failed` to check for `DOING_AJAX` in addition to `is_admin()`. Currently, every request to `admin-ajax.php` will induce the remote request.

**Comment by sudar** [comment]
#54 is merged, hence closing this.
