### ISSUE TITLE
get_user_attribute deprecated notice on VIP Go.

### ISSUE THREAD

**Issue by mattheu** [10up/brightcove-video-connect#85]
As of VIP 2.0.0, the `get_user_attribute` and associated functions are deprecated. 

I believe VIP 2.0.0 is what is running for VIP go sites. My assumption is that it not running on on WP.com VIP, but I am not certain of this.

I don't have a great solution. I don't see any way to easily tell what version of VIP is running. But I wanted to raise a ticket as the notices are a bit of a pain! I will open a ticket with VIP to ask their advice on this.

**Comment by sudar** [comment]
@mattheu 

As you mentioned, right now I can find a way to distinguish between VIP Go, VIP 2.0.0 and Classic VIP.

If there is a way to do that, then we can add the required condition to use either `get_user_attribute` or `get_user_meta`.

**Comment by sudar** [comment]
We reached out to VIP and got the following response.

> Ideally you should leave the plugin as is so that it doesn't need to have any custom environment flags. We're internally discussing the possibility to exclude deprecated function messages from production as we need them to exist to allow for 1-1 parity with WP.com VIP as we work through transition clients between environments.

I am going to close this issue, since we can do any code change for it.
