### ISSUE TITLE
Support for Advanced Embed Code

### ISSUE THREAD

**Issue by harniman** [10up/brightcove-video-connect#89]
Brightcove provides iFrame and Advanced Embed code options. Plugin only supports iFrame today.

For some use cases, and to interact with other elements of the hosting page, it is sometimes required to use the Advanced Embed option.

High level requirements:

- low admin to set the default behaviour for the account - ie use iFrame or Advanced Embed
- Allow selection of the embed mode for each insertion of a video - defaults based on default set by admin (above)
- Sensible default behaviours for existing entries - ie if no option set, assume iFrame so we don't break existing functionality
- Preview to support the chosen embed option

**Comment by bc-timbaldwin** [comment]
V1.4 covers these requirements, except to preview the actual embed option you still have to insert the short code on a page and then preview there.  The preview in the insert embed dialog still just previews the video itself.
