### ISSUE TITLE
Review the number of metadata fields displayed in plugin

### ISSUE THREAD

**Issue by adamwilliams78** [10up/brightcove-video-connect#90]
We currently display all custom metadata fields in the plugin, however most of these are not required in  the Wordpress plugin as editors do not need to use them (there is also a risk they could edit them and break the workflow). Could we somehow add a config setting to hide this? Here's a grab of the dozen or so custom fields we currently expose:

<img width="918" alt="screen shot 2017-03-16 at 10 56 25" src="https://cloud.githubusercontent.com/assets/22640728/23993145/5f084b82-0a37-11e7-9420-d7dd79e9dfaa.png">

**Comment by allan23** [comment]
@adamwilliams78, since these are custom fields from Brightcove, we recommend that if you do not want them shown to use JavaScript or CSS to hide them from your editors.
