### ISSUE TITLE
Video tags does not automatically pull

### ISSUE THREAD

**Issue by panupongvmaqe** [10up/brightcove-video-connect#99]
Video tags does not automatically pull from Brightcove account.
Videos are pulling correctly with tags attach respectively but it does not show on the tags filter dropdown.
However, if the tag is edited directly inside Wordpress, the tags filter dropdown will show the newly edited tag and sync up to Brightcove correctly.
Wordpress 4.8
Brightcove video connect 1.3.2
All exposed Brightcove APIs permission is granted

**Comment by silevitas** [comment]
WP will include the local tags in the WP install (as you've seen), but the complete set of tags in a Video Cloud account is not available via any API. Maybe one day!

I suppose you could in theory store copies of the metadata of content and gradually fill up the tags list in the WP install...
